import type { ImportedUrl, MobileCandidate } from './quality';
export const COLUMN_FIELDS = ['company_name','phone','mobile_phone','address','prefecture','website_url','instagram_url','status','memo','last_call_date'] as const;
export type ColumnField=typeof COLUMN_FIELDS[number];
export const COLUMN_LABELS:Record<ColumnField,string>={company_name:'会社名',phone:'電話番号',mobile_phone:'携帯番号',address:'住所',prefecture:'都道府県',website_url:'HP URL',instagram_url:'Instagram URL',status:'営業状況',memo:'メモ',last_call_date:'最終架電日'};
export interface SheetMapping {mappingSource?:string;supplementaryUrlColumns?:number[];confidence?:number;needs_review?:boolean;warnings?:string[];columnCount?:number;sheet:string;enabled:boolean;headerRow:number;columns:Partial<Record<ColumnField,number>>;historyColumns:number[];prefecture:string;headers:string[];samples:string[][];rowCount:number;}
export interface ImportRow {phone_candidates?:import('./phones').PhoneCandidate[];raw_last_call_date?:string;import_metadata?:Record<string,unknown>; raw_website_url?:string; imported_urls?:ImportedUrl[]; mobile_candidates?:MobileCandidate[]; closure_state?:'normal'|'pending'|'confirmed'; closure_reason?:string;source_file:string;file_hash:string;source_sheet:string;source_row:number;company_name:string;normalized_company_name:string;phone:string;normalized_phone:string;normalized_phones:string[];mobile_phone:string;address:string;normalized_address:string;prefecture:string;website_url:string;instagram_url:string;raw_company_name:string;raw_phone:string;raw_status:string;raw_memo:string;raw_history:string;raw_data:Record<string,string>;call_status:string;last_call_date:string|null;call_memo:string;is_do_not_call:boolean;is_closed:boolean;eligible_for_sales:boolean;exclusion_reason:string;}
export interface ImportOutcome {source_sheet:string;source_row:number;kind:'new'|'existing'|'duplicate_candidate'|'error';company_id:string|null;candidate_ids:string[];excluded:boolean;count_excluded?:boolean;message:string;}
export interface Counts {read:number;new:number;existing:number;duplicate_candidate:number;excluded:number;errors:number;}
export interface ImportJob {id:string;runId?:string;sourceFile:string;fileHash:string;status:'inspecting'|'ready'|'queued'|'running'|'completed'|'failed';createdAt:string;updatedAt:string;startedAt?:string;durationMs:number;processed:number;limit:number;counts:Counts;mappings:SheetMapping[];error?:string;}
