import Link from 'next/link';
import { searchCompanies } from '@/lib/store';
import { PREFECTURES } from '@/lib/normalize';
import { createCompany } from '../actions';
export default async function Companies({searchParams}:{searchParams:Promise<{q?:string;prefecture?:string;error?:string;page?:string}>}) {
 const params=await searchParams;const q=params.q?.trim()??'';const page=Math.max(1,Math.min(100000,Number(params.page)||1));const {companies,total}=await searchCompanies(q,params.prefecture??'',Math.floor(page));
 const pageLink=(p:number)=>'/companies?'+new URLSearchParams({q,prefecture:params.prefecture??'',page:String(p)}).toString();
 return <><h1>会社一覧</h1>{params.error&&<p role="alert" className="text-red-700 mb-4">{params.error}</p>}<section><form className="flex gap-3 flex-wrap" method="get"><input className="flex-1" name="q" defaultValue={q} placeholder="会社名・電話番号" aria-label="会社名・電話番号"/><select className="flex-1" name="prefecture" defaultValue={params.prefecture??''} aria-label="都道府県"><option value="">すべての都道府県</option>{PREFECTURES.map(p=><option key={p}>{p}</option>)}</select><button>検索</button><Link href="/companies">リセット</Link></form></section><section className="overflow-x-auto"><p className="mb-3">{total}社</p><table><thead><tr>{['会社名','エリア','電話番号','HP','Instagram','既存マスター','営業状況'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{companies.map(c=><tr key={c.id}><td><Link href={`/companies/${c.id}`}>{c.company_name}</Link></td><td>{c.prefecture}</td><td>{c.phone||c.mobile_phone||'未登録'}</td><td>{c.website_url?<a href={c.website_url} target="_blank" rel="noreferrer">HP</a>:'—'}</td><td>{c.instagram_url?<a href={c.instagram_url} target="_blank" rel="noreferrer">Instagram</a>:'—'}</td><td>{c.existing_master?'あり':'なし'}</td><td>{c.eligible_for_sales===false?(c.exclusion_reason||c.call_status):c.is_do_not_call?'営業禁止':c.call_status}</td></tr>)}</tbody></table>{!companies.length&&<p className="mt-3">該当する会社はありません。</p>}<div className="flex gap-4 mt-4">{page>1&&<Link href={pageLink(page-1)}>前の100件</Link>}<span>{page}ページ</span>{page*100<total&&<Link href={pageLink(page+1)}>次の100件</Link>}</div></section><section><h2>会社を登録</h2><form action={createCompany} className="grid sm:grid-cols-2 gap-4">{[['company_name','会社名（必須）'],['phone','電話番号'],['mobile_phone','携帯番号'],['prefecture','都道府県'],['address','住所'],['website_url','HP URL'],['instagram_url','Instagram URL'],['google_maps_url','Google Maps URL'],['goopit_url','グーピット URL']].map(([name,label])=><label key={name}>{label}<input name={name} required={name==='company_name'} type={name.endsWith('_url')?'url':'text'} maxLength={name==='company_name'?200:2000}/></label>)}<label><input type="checkbox" name="existing_master"/> 既存マスターに掲載あり</label><div><button>会社を保存</button></div></form><p className="mt-3 text-sm text-slate-500">電話一致、または正規化会社名と所在地の一致を重複候補として確認します。</p></section></>;
}
